### ISSUE TITLE
haxelib doesn't get isolated to each version?

### ISSUE THREAD

**Issue by zabojad** [kLabz/haxe-manager#4]
I just installed haxe-manager on os x (see https://github.com/kLabz/haxe-manager/pull/3) and it seems that my local haxelib is still the one from my old pkg installed Haxe 3.4.4.

Shouldn't we manage one Haxelib per Haxe version?

**Comment by kLabz** [comment]
Haxelib is supposed to be included in the archive used by haxe-manager. At least for linux it is.

**Comment by zabojad** [comment]
You are right. I was misleading because the installed haxe libs do not get isolated by haxe version, which is bad in my opinion...
